apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    machineType: aarch64-virt
    emulatedMachines:
      - "aarch64-virt"
    cpuModel: "host-model"
