apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-testvm
  labels:
    kubevirt.io/size: medium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
