---
apiVersion: vitistack.io/v1alpha1
kind: Machine
metadata:
  name: example-machine-medium-with-overrides
spec:
  machineClass: "medium"
  name: "example-vm-medium-with-overrides"
  provider: kubevirt
  memory: 3221225472 # 3 GB in bytes - overrides MachineClass default
  cpu:
    cores: 3 # Override MachineClass default
