---
apiVersion: vitistack.io/v1alpha1
kind: Machine
metadata:
  name: example-machine-iso-debian-arm64
  annotations:
    # Annotation to indicate we want to use a DataVolume for the boot source
    kubevirt.io/boot-source: "datavolume"
    kubevirt.io/boot-source-type: "http"
spec:
  machineClass: "small"
  name: "debian-iso-vm-arm64"
  provider: kubevirt

  # Operating system configuration
  os:
    family: linux
    distribution: debian
    version: "13.3"
    architecture: arm64
    # HTTP URL to the debian ISO image
    # This will be used to create a DataVolume with CDI
    imageID: "https://cdimage.debian.org/debian-cd/current/arm64/iso-cd/debian-13.3.0-arm64-netinst.iso"

  # Define disks - the ISO will be attached as a cdrom
  disks:
    - name: "root"
      sizeGB: 20
      boot: true
      type: "virtio"
      encrypted: false
