---
# Example: Machine with cloud-init from a Secret
# Useful when cloud-init data contains sensitive information like passwords
apiVersion: vitistack.io/v1alpha1
kind: Machine
metadata:
  name: example-cloudinit-secret
spec:
  machineClass: "medium"
  name: "cloudinit-secret-vm"
  provider: kubevirt

  os:
    family: linux
    distribution: ubuntu
    version: "24.04"
    architecture: amd64
    imageID: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"

  disks:
    - name: "root"
      sizeGB: 20
      boot: true
      type: "virtio"

  # Cloud-init configuration referencing a Secret
  cloudInit:
    type: noCloud
    userDataSecretRef:
      name: vm-cloudinit-secret
      key: userdata # Optional, defaults to "userdata"

---
# Secret containing cloud-init user data
# Note: In a real scenario, you would create this secret separately
# possibly using kubectl create secret or sealed-secrets
apiVersion: v1
kind: Secret
metadata:
  name: vm-cloudinit-secret
type: Opaque
stringData:
  userdata: |
    #cloud-config
    hostname: cloudinit-secret-vm
    users:
      - name: admin
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /bin/bash
        # Password hash for 'changeme' - change this!
        passwd: $6$rounds=4096$xyz...
        lock_passwd: false
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQ... your-ssh-key
    chpasswd:
      expire: true
    ssh_pwauth: true
    packages:
      - curl
      - vim
    runcmd:
      - systemctl enable ssh
      - systemctl start ssh
