---
apiVersion: vitistack.io/v1alpha1
kind: Machine
metadata:
  name: example-machine-small-ish
spec:
  # Using predefined small machine class
  machineClass: "small"
  provider: kubevirt
  # Override MachineClass defaults with custom resources
  name: "example-vm-small"
  cpu:
    # Override default CPU from MachineClass
    cores: 4
    sockets: 4
    threadsPerCore: 2
  memory: 4294967296 # 4 GB in bytes - overrides MachineClass default

