---
apiVersion: vitistack.io/v1alpha1
kind: Machine
metadata:
  name: example-machine-iso-ubuntu
  annotations:
    # Annotation to indicate we want to use a DataVolume for the boot source
    kubevirt.io/boot-source: "datavolume"
    kubevirt.io/boot-source-type: "http"
spec:
  machineClass: "medium"
  name: "ubuntu-iso-vm"
  provider: kubevirt

  # Operating system configuration
  os:
    family: linux
    distribution: ubuntu
    version: "24.04"
    architecture: amd64
    # HTTP URL to the Ubuntu ISO image
    # This will be used to create a DataVolume with CDI
    imageID: "https://releases.ubuntu.com/24.04.3/ubuntu-24.04.3-live-server-amd64.iso"

  # Define disks - the ISO will be attached as a cdrom
  disks:
    - name: "root"
      sizeGB: 50
      boot: true
      type: "virtio"
      encrypted: false
